# Generated by Django 3.1.3 on 2020-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, default='Alemhar', max_length=255, null=True, verbose_name='First Name'),
        ),
    ]
