# Generated by Django 3.1.3 on 2020-11-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201122_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
    ]
